name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Publish to GitHub Packages
        run: ./mvnw deploy
        env:
          EX_UNIFIER_ACTION_TOKEN: ${{ secrets.EX_UNIFIER_ACTION_TOKEN }}
          GPG_TTY: /dev/console

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Configure Maven
        run: |
          mkdir -p $HOME/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.EX_UNIFIER_ACTION_TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml

      - name: Build and deploy with Maven
        run: mvn deploy
        env:
          EX_UNIFIER_ACTION_TOKEN: ${{ secrets.EX_UNIFIER_ACTION_TOKEN }}
          GPG_TTY: /dev/console
